apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: add-imagepullsecrets
  annotations:
    policies.kyverno.io/title: Add imagePullSecrets
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images coming from certain registries require authentication in order to pull them,
      and the kubelet uses this information in the form of an imagePullSecret to pull
      those images on behalf of your Pod. This policy searches for images coming from a
      registry called `corp.reg.com` and, if found, will mutate the Pod to add an
      imagePullSecret called `my-secret`.
spec:
  autogen:
    podControllers:
      controllers:
      - deployments
      - jobs
      - cronjobs
      - statefulsets
      - daemonsets
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  matchConditions:
    - name: require-image-pull-secret
      expression: "object.spec.containers.exists(c, c.image.startsWith('corp.reg.com/')) && !(has(object.spec.imagePullSecrets) && object.spec.imagePullSecrets.exists(s, s.name == 'my-secret'))"
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |-
          has(object.spec.imagePullSecrets) ?
            [JSONPatch{
              op: "add",
              path: "/spec/imagePullSecrets/-",
              value: {"name": "my-secret"}
            }] :
            [JSONPatch{
              op: "add",
              path: "/spec/imagePullSecrets",
              value: [{"name": "my-secret"}]
            }]