apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: add-ndots
  annotations:
    policies.kyverno.io/title: Add ndots
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      The ndots value controls where DNS lookups are first performed in a cluster
      and needs to be set to a lower value than the default of 5 in some cases.
      This policy mutates all Pods to add the ndots option with a value of 1.
spec:
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["pods"]
  matchConditions:
  - name: needs-ndots
    expression: |
      !has(object.spec.dnsConfig) || 
      !has(object.spec.dnsConfig.options) ||
      !object.spec.dnsConfig.options.exists(opt, opt.name == "ndots")
  mutations:
  - patchType: JSONPatch
    jsonPatch:
      expression: |
        has(object.spec.dnsConfig) && has(object.spec.dnsConfig.options) ?
        [JSONPatch{
          op: "add",
          path: "/spec/dnsConfig/options/-",
          value: {"name": "ndots", "value": "1"}
        }] :
        (has(object.spec.dnsConfig) ?
          [JSONPatch{
            op: "add",
            path: "/spec/dnsConfig/options",
            value: [{"name": "ndots", "value": "1"}]
          }] :
          [JSONPatch{
            op: "add",
            path: "/spec/dnsConfig",
            value: {"options": [{"name": "ndots", "value": "1"}]}
          }]
        )